# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft and contributors.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AzureEntityResource
    from ._models_py3 import CustomLocation
    from ._models_py3 import CustomLocationOperation
    from ._models_py3 import CustomLocationPropertiesAuthentication
    from ._models_py3 import EnabledResourceType
    from ._models_py3 import EnabledResourceTypePropertiesTypesMetadataItem
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse, ErrorResponseException
    from ._models_py3 import Identity
    from ._models_py3 import PatchableCustomLocations
    from ._models_py3 import ProxyResource
    from ._models_py3 import Resource
    from ._models_py3 import SystemData
    from ._models_py3 import TrackedResource
except (SyntaxError, ImportError):
    from ._models import AzureEntityResource
    from ._models import CustomLocation
    from ._models import CustomLocationOperation
    from ._models import CustomLocationPropertiesAuthentication
    from ._models import EnabledResourceType
    from ._models import EnabledResourceTypePropertiesTypesMetadataItem
    from ._models import ErrorAdditionalInfo
    from ._models import ErrorDetail
    from ._models import ErrorResponse, ErrorResponseException
    from ._models import Identity
    from ._models import PatchableCustomLocations
    from ._models import ProxyResource
    from ._models import Resource
    from ._models import SystemData
    from ._models import TrackedResource
from ._paged_models import CustomLocationOperationPaged
from ._paged_models import CustomLocationPaged
from ._paged_models import EnabledResourceTypePaged
from ._custom_locations_enums import (
    CreatedByType,
    ResourceIdentityType,
    HostType,
)

__all__ = [
    'AzureEntityResource',
    'CustomLocation',
    'CustomLocationOperation',
    'CustomLocationPropertiesAuthentication',
    'EnabledResourceType',
    'EnabledResourceTypePropertiesTypesMetadataItem',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse', 'ErrorResponseException',
    'Identity',
    'PatchableCustomLocations',
    'ProxyResource',
    'Resource',
    'SystemData',
    'TrackedResource',
    'CustomLocationOperationPaged',
    'CustomLocationPaged',
    'EnabledResourceTypePaged',
    'CreatedByType',
    'ResourceIdentityType',
    'HostType',
]
