# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft and contributors.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.paging import Paged


class CustomLocationOperationPaged(Paged):
    """
    A paging container for iterating over a list of :class:`CustomLocationOperation <azure.mgmt.extendedlocation.v2021_08_15.models.CustomLocationOperation>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[CustomLocationOperation]'}
    }

    def __init__(self, *args, **kwargs):

        super(CustomLocationOperationPaged, self).__init__(*args, **kwargs)
class CustomLocationPaged(Paged):
    """
    A paging container for iterating over a list of :class:`CustomLocation <azure.mgmt.extendedlocation.v2021_08_15.models.CustomLocation>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[CustomLocation]'}
    }

    def __init__(self, *args, **kwargs):

        super(CustomLocationPaged, self).__init__(*args, **kwargs)
class EnabledResourceTypePaged(Paged):
    """
    A paging container for iterating over a list of :class:`EnabledResourceType <azure.mgmt.extendedlocation.v2021_08_15.models.EnabledResourceType>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[EnabledResourceType]'}
    }

    def __init__(self, *args, **kwargs):

        super(EnabledResourceTypePaged, self).__init__(*args, **kwargs)
